const STATES=window.US_STATE_ADMISSIONS.sort((a,b)=>a.order-b.order);
const groupLabels={original:"13개 원주",frontier:"초기 내륙 확장",louisiana:"루이지애나권",mexican:"서남부 확장",pacific:"태평양권",late:"20세기 편입"};
const stateById=new Map(STATES.map(s=>[s.id,s]));
const stateByOrder=new Map(STATES.map(s=>[s.order,s]));
const stateByAbbr=new Map(STATES.map(s=>[s.abbr,s]));
const fmtNumber=new Intl.NumberFormat("ko-KR");
const fmtArea=new Intl.NumberFormat("ko-KR",{maximumFractionDigits:2});
const fmtDate=new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric"});
let currentStep=1;
let selectedState=stateByOrder.get(1);
let features=[];
let playTimer=null;
const svg=d3.select("#map");
const mapStage=document.getElementById("mapStage");
const tooltip=document.getElementById("tooltip");
function flagUrl(s){return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(s.flag)}`}
function formatDate(v){return fmtDate.format(new Date(`${v}T00:00:00`))}
function shortDate(v){const [y,m,d]=v.split("-");return `${y}.${m}.${d}`}
function getSummary(s){const status=s.order<=currentStep?"현재 타임라인에서는 이미 연방에 편입된 상태입니다.":"현재 타임라인에서는 아직 편입 전입니다.";return `${s.ko}는 ${formatDate(s.admitted)}에 ${s.order}번째 주로 연방에 가입했습니다. ${groupLabels[s.group]} 흐름에 속하며, 주도는 ${s.capitalKo}, 최대 도시는 ${s.largestKo}입니다. ${status}`}
function updateStatePanel(s){selectedState=s;document.getElementById("flagImage").src=flagUrl(s);document.getElementById("flagImage").alt=`${s.ko} 주기`;document.getElementById("stateKicker").textContent=`${s.order}번째 가입`;document.getElementById("stateName").textContent=s.ko;document.getElementById("stateEnglish").textContent=s.en;document.getElementById("stateAbbr").textContent=s.abbr;document.getElementById("stateSummary").textContent=getSummary(s);document.getElementById("admissionDate").textContent=`${formatDate(s.admitted)} (${s.order}번째)`;document.getElementById("capital").textContent=`${s.capitalKo} / ${s.capital}`;document.getElementById("largestCity").textContent=`${s.largestKo} / ${s.largest}`;document.getElementById("area").textContent=`${fmtArea.format(s.area)} km²`;document.getElementById("population").textContent=`${fmtNumber.format(s.population)}명 (2020년)`;document.getElementById("houseSeats").textContent=`${s.house}석`}
function updateNextList(){const list=document.getElementById("nextList");const upcoming=STATES.filter(s=>s.order>currentStep).slice(0,4);if(!upcoming.length){list.innerHTML=`<div class="next-item" role="button" tabindex="0"><b>완료</b><span>50개 주가 모두 편입되었습니다.</span><span>1959</span></div>`;return}list.innerHTML=upcoming.map(s=>`<div class="next-item" role="button" tabindex="0" data-abbr="${s.abbr}"><b>${s.order}</b><span>${s.ko}<br>${shortDate(s.admitted)}</span><span>${s.abbr}</span></div>`).join("");list.querySelectorAll(".next-item[data-abbr]").forEach(item=>{item.addEventListener("click",()=>setStep(stateByAbbr.get(item.dataset.abbr).order,true));item.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setStep(stateByAbbr.get(item.dataset.abbr).order,true)}})})}
function renderMap(){if(!features.length)return;const bounds=mapStage.getBoundingClientRect();const width=Math.max(360,bounds.width);const height=Math.max(360,bounds.height);svg.attr("viewBox",`0 0 ${width} ${height}`);const projection=d3.geoAlbersUsa().fitSize([width-34,height-34],{type:"FeatureCollection",features});const path=d3.geoPath(projection);const states=svg.selectAll("path.state").data(features,f=>f.id);states.enter().append("path").attr("class","state future").attr("tabindex",0).attr("role","button").on("click",(_,f)=>{const s=stateById.get(f.id);if(s){updateStatePanel(s);updateMapClasses()}}).on("keydown",(e,f)=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();const s=stateById.get(f.id);if(s){updateStatePanel(s);updateMapClasses()}}}).on("mousemove",(e,f)=>{const s=stateById.get(f.id);if(!s)return;tooltip.style.display="block";tooltip.style.left=`${e.offsetX}px`;tooltip.style.top=`${e.offsetY}px`;tooltip.innerHTML=`<strong>${s.ko} (${s.abbr})</strong>${s.order}번째 가입 · ${shortDate(s.admitted)}`}).on("mouseleave",()=>{tooltip.style.display="none"}).merge(states).attr("d",path).attr("aria-label",f=>{const s=stateById.get(f.id);return s?`${s.ko}, ${s.order}번째 가입`:"주"});states.exit().remove();updateMapClasses()}
function updateMapClasses(){svg.selectAll("path.state").attr("class",f=>{const s=stateById.get(f.id);if(!s)return"state future";const parts=["state"];if(s.order<=currentStep)parts.push("admitted",s.group);else parts.push("future");if(s.order===currentStep)parts.push("current");if(selectedState&&selectedState.id===s.id)parts.push("selected");return parts.join(" ")})}
function setStep(step,selectCurrent=true){currentStep=Math.max(1,Math.min(50,Number(step)));const s=stateByOrder.get(currentStep);const year=s.admitted.slice(0,4);document.getElementById("timeline").value=currentStep;document.getElementById("metricYear").textContent=year;document.getElementById("metricCount").textContent=`${currentStep}/50`;document.getElementById("metricState").textContent=s.abbr;document.getElementById("yearLabel").textContent=year;document.getElementById("eventLabel").textContent=`${s.ko} 연방 가입`;document.getElementById("progressFill").style.width=`${currentStep/50*100}%`;updateStatePanel(selectCurrent?s:selectedState);updateNextList();updateMapClasses()}
function stopPlayback(){if(playTimer){clearInterval(playTimer);playTimer=null}document.getElementById("playBtn").innerHTML='<i data-lucide="play"></i>';document.getElementById("playBtn").title="재생";document.getElementById("playBtn").setAttribute("aria-label","재생");if(window.lucide)lucide.createIcons()}
function startPlayback(){if(currentStep>=50)setStep(1,true);document.getElementById("playBtn").innerHTML='<i data-lucide="pause"></i>';document.getElementById("playBtn").title="정지";document.getElementById("playBtn").setAttribute("aria-label","정지");if(window.lucide)lucide.createIcons();playTimer=setInterval(()=>{if(currentStep>=50){stopPlayback();return}setStep(currentStep+1,true)},880)}
document.getElementById("timeline").addEventListener("input",e=>{stopPlayback();setStep(e.target.value,true)});
document.getElementById("resetBtn").addEventListener("click",()=>{stopPlayback();setStep(1,true)});
document.getElementById("prevBtn").addEventListener("click",()=>{stopPlayback();setStep(currentStep-1,true)});
document.getElementById("nextBtn").addEventListener("click",()=>{stopPlayback();setStep(currentStep+1,true)});
document.getElementById("playBtn").addEventListener("click",()=>{if(playTimer)stopPlayback();else startPlayback()});
window.addEventListener("resize",()=>renderMap());
async function init(){if(window.lucide)lucide.createIcons();updateStatePanel(selectedState);updateNextList();setStep(1,true);try{const us=await d3.json("https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json");features=topojson.feature(us,us.objects.states).features.filter(f=>stateById.has(f.id));renderMap()}catch(error){console.error(error);document.getElementById("errorBox").classList.add("show")}}
init();
